### PR TITLE
Aerzy patch 1

### PR DESCRIPTION
**Pull request by aerzy**

### CODE REVIEW

**Comment by MasterDomino** [comment]
@aerzy Emm... Are you sure about that?

**Comment by BlowaXD** [comment]
Obviously someone that does not know how to use git.

You are merging on the wrong repository, Kevin.
You want to merge OpenNos in your branch

**Comment by varunhardgamer** [comment]
@MasterDomino

**Comment by MasterDomino** [comment]
WOOOOT?

**Comment by varunhardgamer** [comment]
@MasterDomino 😂😂😂😂😂😂

**Comment by MasterDomino** [comment]
@varunhardgamer Okay are you maybe intoxicated?

**Pull request closed without merging**
