### PR TITLE
Hitqueue

### PR DESCRIPTION
**Pull request by PsykoBoss**

### CODE REVIEW

**Comment by Ciapa** [comment]
Nope.

**Comment by chucktheripper** [comment]
We cannot merge the branch, as it is not completed.

**Comment by PsykoBoss** [comment]
How I do update your fix without downloading each time all files? They told me to make a pull request

**Comment by Ciapa** [comment]
TBH, if you can't work with git basics, please don't try to host your own server. Better leave rhe OpenNos Project as is.

**Comment by PsykoBoss** [comment]
I want to say how i update the fix, I think that anyone that have access to the data are free to try to open your own server, also only to learn -.-" You want to help me or do you still just want to say that I'm not capable?

**Comment by Ciapa** [comment]
@PsykoBoss To give own commits to the hitqueue branch, you need to create a PR from your own fork TO the hitqueue branch. If you can't do that, you're not capaoble, sorry bro.

**Comment by chucktheripper** [comment]
You actually wanted to branch OUR hitqueue branch to OUR master branch.

**Pull request closed without merging**
